main:
  - identifier: home
    name: Home
    pageRef: /
    pre: home
    weight: 1
  - identifier: about
    name: About
    pageRef: /about.html
    pre: user
    weight: 2
  - identifier: example
    name: Example
    pre: angles-down
    weight: 3
  - identifier: syntax
    name: Syntax Highlighting
    pageRef: /post/09-syntax-highlighting
    weight: 1   
    parent: example
  - identifier: math
    name: Math Formula
    pageRef: /post/10-math-formula
    weight: 2   
    parent: example
    parent: example
  - identifier: flow-charts
    name: Flow Charts
    pageRef: /post/11-mermaid-charts
    weight: 3
    parent: example
  - identifier: archives
    name: Archives
    pageRef: /archives
    pre: archive
    weight: 4
